### ISSUE TITLE
P.46 slices.rs

### ISSUE THREAD

**Issue by vbauerster** [PacktPublishing/Mastering-RUST-Second-Edition#1]
Page 46 says that `slices.rs` code won't compile without extra pair of braces, but it compiles fine without them:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d0eb3a32ece5ac6bdfad6036204faa81

**Comment by creativcoder** [comment]
Hi @vbauerster. 
The reason the code in the [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d0eb3a32ece5ac6bdfad6036204faa81) compiles is because it has the newer version of the compiler. (I think this change is part of the non-lexical lifetimes feature)

The first chapter in the book mentions the compiler version used as `1.32.0`. I have tested it locally with compiler version: 
```
1.32.0-x86_64-unknown-linux-gnu installed - rustc 1.32.0 (9fda7c223 2019-01-16)
```
and indeed the example does not compile:
```rust
error[E0502]: cannot borrow `numbers` as mutable because it is also borrowed as immutable
  --> slice.rs:11:41
   |
6  |         let all: &[u8] = &numbers[..];
   |                           ------- immutable borrow occurs here
...
11 |         let first_two: &mut [u8] = &mut numbers[0..2];
   |                                         ^^^^^^^ mutable borrow occurs here
...
17 | }
   | - immutable borrow ends here
```

Hope this helps!
